version: '3'
# services:
#   cas:
#     build: .
#     ports:
#      - "8443:8443"
#      - "8080:8080"

services:
  open-oauth2playground:
    image: open-oauth2playground:v1.0
    container_name: open-oauth2playground # docker run时指定容器名
    restart: always
    ports:
    - "8081:88"  # docker run时指定端口
    environment:
      CAS_SERVER_NAME: "http://cas-demo:8444"  # 使用 'cas' 作为主机名
    volumes:
      - ./update_cfg.sh:/update_cfg.sh # 路径不对
      - ./cfg.json:/app/Open-OAuth2Playground/cfg.json
    command: ["/bin/bash", "-c", "/update_cfg.sh"]
  cas-demo:
    image: apereo/cas:v6.5.9
    container_name: cas-demo
    restart: always
    ports:
     - "8444:8444"
     - "8080:8080"
    environment:
      CAS_SERVER_NAME: "http://47.100.188.236:8444"  # 设置您的 CAS_SERVER_NAME 环境变量
      SERVER_PORT: "8444"  # 设置您的 SERVER_PORT 环境变量
    volumes:
      - ./cas_init_script.sh:/cas-overlay/cas_init_script.sh
    entrypoint: ["/bin/bash", "-c"]
    command: ["/cas-overlay/cas_init_script.sh && java -server -noverify -Xmx2048M -jar /cas-overlay/cas.war"]