version: '3'
services:
  redis:
    image: redis:latest
    container_name: oauth-redis
    ports:
      - "6379:6379"
  open-oauth2playground:
    image: open-oauth2playground:v2.0
    container_name: open-oauth2playground
    restart: always
    ports:
      - "8085:8080"
    volumes:
      - ./cfg-docker.json:/app/Open-OAuth2Playground/cfg.json
    command: ["/app/Open-OAuth2Playground/OAuth2Playground"]
  oauth-server-lite:
#    image: ecnunic/oauth-server-lite:v1.0
    image: lite-server-test:0716
    container_name: oauth-server-lite
    depends_on:
      - redis
    restart: always
    environment:
      - CLIENT_HOST=127.0.0.1
    ports:
      - "80:80"
      - "8444:8444"