# 启动命令: docker-compose -p open-oauth2playground up -d
# -p [service name] 其中 server_name 可以替换为任意的服务名称

# container model: 容器模式。由 open-oauth2playground 容器网络统一暴露端口
# container 模式下的容器无法暴露自身端口

services:

  open-oauth2playground:
    image: ecnunic/open-oauth2playground:v0.2.0
    container_name: open-oauth2playground
    environment:
      - PLAYGROUND_PORT=80                      # oauth2playground 服务端口号
      - PLAYGROUND_HOST=localhost               # oauth2playground 服务地址/域名 (用于配置域名解析)
      - CAS_SERVER_HOST=localhost               # apereo-cas 服务地址/域名 (用于配置域名解析)
      - OAUTH_SERVER_PORT=8081                  # oauth-server-lite 服务端口号
      - OAUTH_SERVER_HOST=localhost             # oauth-server-lite 服务地址/域名 (用于服务通信 && 配置域名解析)
      - OAUTH_SERVER_URL=http://localhost:8081  # oauth-server-lite 服务 URL
    ports:
      - "80:80"       # open-oauth2playground 端口
      # - "6379:6379"   # redis 端口
#      - "8080:8080"   # apereo-cas 后端服务占用
      - "8081:8081"   # oauth-server-lite 前端服务
      - "8444:8444"   # apereo-cas 前端服务占用
    networks:
      - open-oauth2playground
  #    volumes:
  #      - ./oauth-server-lite/oauth2playground/cfg.json:/app/cfg.json
  #      - ./oauth-server-lite/oauth2playground/logs:/app/logs
    restart: always

  redis:
    image: redis:alpine
    container_name: oauth-redis
    depends_on:
      - open-oauth2playground
    network_mode: container:open-oauth2playground
    restart: always

  oauth-server-lite:
    image: ecnunic/oauth-server-lite:v0.3.0
    container_name: oauth-server-lite
    environment:
      - OAUTH_CLIENT_ID=oauth                 # OAuth2 Client ID
      - OAUTH_CLIENT_SECRET=123456            # OAuth2 Client Secret
      - CAS_USERNAME=cas                      # CAS 用户名
      - CAS_PASSWORD=123456                   # CAS 用户密码
      - OAUTH_SERVER_PORT=8081                # oauth-server-lite 服务端口号
      - CAS_SERVER_PORT=8444                  # apereo-cas 服务端口号
      - CAS_SERVER_HOST=localhost             # apereo-cas 服务地址/域名
      - CAS_SERVER_URL=http://localhost:8444  # apereo-cas 服务 URL
      - OAUTH_REDIS_DSN=localhost:6379        # redis 服务地址/域名
      - OAUTH_REDIS_PASSWORD=                 # redis 服务连接密码
      - PLAYGROUND_HOST=localhost             # oauth2playground 服务地址/域名
      - PLAYGROUND_PORT=80                    # oauth2playground 服务端口号
    depends_on:
      - open-oauth2playground
      - redis
    network_mode: container:open-oauth2playground
#    volumes:
#      - ./oauth-server-lite/apereo-cas/cas.db:/app/apereo-cas/cas.db                       # apereo-cas 用户信息 sqlite 数据库
#      - ./oauth-server-lite/apereo-cas/config:/etc/cas/config                              # apereo-cas 配置信息
#      - ./oauth-server-lite/apereo-cas/services:/etc/cas/services                          # apereo-cas 服务配置
#      - ./oauth-server-lite/oauth-server-lite/sqlite.db:/app/oauth-server-lite/sqlite.db   # oauth-server-lite 认证信息 sqlite 数据库
#      - ./oauth-server-lite/oauth-server-lite/cfg.json:/app/oauth-server-lite/cfg.json     # oauth-server-lite 配置信息
#      - ./oauth-server-lite/oauth-server-lite/logs:/app/oauth-server-lite/logs             # oauth-server-lite 日志
    restart: always

networks:
  open-oauth2playground:
    driver: bridge