# docker-compose -p oauth-server-lite up -d

services:

  redis:
    image: redis:alpine
    container_name: oauth-redis
    ports:
      - "6379:6379"
    networks:
      - oauth-server-lite

  open-oauth2playground:
    image: ecnunic/open-oauth2playground:v0.2.0
    container_name: open-oauth2playground
    environment:
      - PLAYGROUND_PORT=80
      - OAUTH_SERVER_PORT=8081
      - OAUTH_SERVER_HOST=oauth-server-lite
      - OAUTH_SERVER_URL=http://oauth-server-lite:8081
    restart: always
    ports:
      - "80:80"
    networks:
      - oauth-server-lite
  #    volumes:
  #      - ./oauth-server-lite/oauth2playground/cfg.json:/app/cfg.json
  #      - ./oauth-server-lite/oauth2playground/logs:/app/logs

  oauth-server-lite:
    image: ecnunic/oauth-server-lite:v0.3.0
    container_name: oauth-server-lite
    environment:
      - OAUTH_CLIENT_ID=oauth                 # OAuth2 Client ID
      - OAUTH_CLIENT_SECRET=123456            # OAuth2 Client Secret
      - CAS_USERNAME=cas                      # CAS 用户名
      - CAS_PASSWORD=123456                   # CAS 用户密码
      - OAUTH_SERVER_PORT=8081                # oauth-server-lite 后端服务端口号
      - CAS_SERVER_PORT=8444                  # apereo-cas 服务端口号
      - CAS_SERVER_HOST=localhost             # apereo-cas 服务地址/域名
      - CAS_SERVER_URL=http://localhost:8444  # apereo-cas 服务 URL
      - OAUTH_REDIS_DSN=redis:6379            # redis 服务域名
      - OAUTH_REDIS_PASSWORD=                 # redis 服务连接密码
      - PLAYGROUND_HOST=localhost             # oauth2playground 服务地址/域名
    depends_on:
      - redis
    restart: always
    ports:
      - "8080:8080"   # apereo-cas 服务占用 1
      - "8081:8081"   # oauth-server-lite 前端服务
      - "8444:8444"   # apereo-cas 服务占用 2
    networks:
      - oauth-server-lite
#    volumes:
#      - ./oauth-server-lite/apereo-cas/cas.db:/app/apereo-cas/cas.db                       # apereo-cas 用户信息 sqlite 数据库
#      - ./oauth-server-lite/apereo-cas/config:/etc/cas/config                              # apereo-cas 配置信息
#      - ./oauth-server-lite/apereo-cas/services:/etc/cas/services                          # apereo-cas 服务配置
#      - ./oauth-server-lite/oauth-server-lite/sqlite.db:/app/oauth-server-lite/sqlite.db   # oauth-server-lite 认证信息 sqlite 数据库
#      - ./oauth-server-lite/oauth-server-lite/cfg.json:/app/oauth-server-lite/cfg.json     # oauth-server-lite 配置信息
#      - ./oauth-server-lite/oauth-server-lite/logs:/app/oauth-server-lite/logs             # oauth-server-lite 日志

networks:
  oauth-server-lite:
    driver: bridge