# Application properties that need to be
# embedded within the web application can be included here
server:
  cors:
    allowed-origins: "*" # 允许所有域名
    allowed-methods: GET,POST # 允许的方法
    allowed-headers: "*" # 允许的头部
    allow-credentials: true # 是否允许凭证
    max-age: 3600 # 预检请求的缓存时间
